#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_region="${0##*/}"
  
  export AWS_PROFILE="${AWS_PROFILE_PREFIX:-}${nm_region}${AWS_PROFILE_SUFFIX:-}" 
  exec aws "$@"
}

source sub "$BASH_SOURCE" "$@"
