#!/usr/bin/env bash

function main {
  local shome="${_awesome_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  aws ec2 describe-regions | jq -r '.Regions | sort_by(.RegionName)[].RegionName'
}

source sub "$BASH_SOURCE" "$@"
