#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  "$shome/vendor/virtualenv/bin/awslimitchecker" --skip-ta "$@" 2>&1 | grep -v 'AGPL-licensed free software'
}

source sub "$BASH_SOURCE" "$@"
