#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_region="${0##*/}"
  nm_region="${nm_region#aws-}"
  
  if [[ -n "${DEBUG:-}" ]]; then
    set -x
  fi
  export AWS_PROFILE="${CONTEXT_ACCOUNT:+$CONTEXT_ACCOUNT-}${CONTEXT_ENV:+$CONTEXT_ENV-}${nm_region}" 
  exec aws "$@"
}

source sub "$BASH_SOURCE" "$@"
