#!/usr/bin/env bash

function main {
  local shome="${_awesome_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  exec runmany "$@" -- $(aws regions)
}

source sub "$BASH_SOURCE" "$@"
