#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$#" in
    0)
      local nm_repo="$(cat ".repo-name")"
      ;;
    *)
  local nm_repo="$1"; shift
      ;;
  esac

  local nm_branch="$(git rev-parse --abbrev-ref HEAD)"

  git remote remove origin || true
  git remote add origin "git@github.com:$nm_repo"
  git fetch origin
  git branch --set-upstream-to "origin/$nm_branch"
}

source sub "$BASH_SOURCE" "$@"
