#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source normalize

  case "${1:-}" in
    wheels)
      export PIP_WHEEL=1
      ;;
  esac

  block compile virtualenv27
  mkdir -p "$shome/bin"
  ln -nfs \
    ../vendor/virtualenv/bin/amicleaner \
    ../vendor/virtualenv/bin/awslimitchecker \
    ../vendor/virtualenv/bin/aws-shell \
    "$shome/bin/"
}

main "$@"
