#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  mkdir -p "$shome/bin"

  local url_awsvault_Darwin="https://github.com/99designs/aws-vault/releases/download/v${AWSVAULT_VERSION}/aws-vault-darwin-amd64"
  local url_awsvault_Linux="https://github.com/99designs/aws-vault/releases/download/v${AWSVAULT_VERSION}/aws-vault-linux-amd64"

  local url_awsvault="url_awsvault_$(uname -s)"
  local fnm_awsvault="$(basename "${!url_awsvault}")"
  cache curl "$fnm_awsvault" "${!url_awsvault}"

  pushd "$shome/bin"
  cp "${DATA}/cache/curl/$fnm_awsvault" "$shome/bin/aws-vault"
  chmod 755 "$shome/bin/aws-vault"
  popd

  local url_chamber_Darwin="https://github.com/segmentio/chamber/releases/download/v${CHAMBER_VERSION}/chamber-v${CHAMBER_VERSION}-darwin-amd64"
  local url_chamber_Linux="https://github.com/segmentio/chamber/releases/download/v${CHAMBER_VERSION}/chamber-v${CHAMBER_VERSION}-linux-amd64"

  local url_chamber="url_chamber_$(uname -s)"
  local fnm_chamber="$(basename "${!url_chamber}")"
  cache curl "$fnm_chamber" "${!url_chamber}"

  pushd "$shome/bin"
  cp "${DATA}/cache/curl/$fnm_chamber" "$shome/bin/chamber"
  chmod 755 "$shome/bin/chamber"
  echo "${CHAMBER_VERSION}" > "$shome/.chamber-version"
  popd

  local url_awsless_Darwin="https://github.com/wallix/awless/releases/download/v${AWLESS_VERSION}/awless-darwin-amd64.tar.gz"
  local url_awsless_Linux="https://github.com/wallix/awless/releases/download/v${AWLESS_VERSION}/awless-linux-amd64.tar.gz"

  local url_awsless="url_awsless_$(uname -s)"
  local fnm_awsless="$(basename "${!url_awsless}")"
  cache curl "$fnm_awsless" "${!url_awsless}"

  pushd "$shome/bin"
  tar xfz  "${DATA}/cache/curl/$fnm_awsless"
  chmod 755 "$shome/bin/awless"
  popd
}

main "$@"
