#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if ! type -P "awslimitchecker" >/dev/null; then
    return 1
  fi

  if ! type -P "ec2-costs" >/dev/null; then
    return 1
  fi

  return 0
}

source sub "$BASH_SOURCE" "$@"
