#!/usr/bin/env bash

function _awesome_profile {
  local shome="${_awesome_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"

  AWSVAULT_VERSION='3.7.1'
  CHAMBER_VERSION='1.6.0'
}

_awesome_profile
